# Dependency Review Configuration
# This file provides configuration for the dependency review GitHub Action

# Fail the action if any of these severity levels are found
fail-on-severity: high

# List of licenses that are explicitly denied
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-3.0
  - LGPL-2.1
  - LGPL-3.0

# List of licenses that are explicitly allowed
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unlicense
  - CC0-1.0

# Fail on packages with these patterns
deny-packages:
  - "malicious-package-*"

# Allow these packages even if they would normally be denied
allow-dependencies-licenses:
  - package: setuptools
    license: MIT
  - package: pip
    license: MIT
  - package: wheel
    license: MIT

# Enable vulnerability checking
vulnerability-check: true

# Enable license checking
license-check: true

# Configuration for comment generation
comment-summary-in-pr: true

# Warn only mode (set to false to fail the action)
warn-only: false

# Additional settings for Python packages
python:
  # Ignore dev dependencies in review
  ignore-dev-dependencies: false
  # Check requirements files
  check-requirements-files: true