name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels: ["feature","enhancement"]
  - title: "🐞 Fixes"
    labels: ["bug","fix","bugfix"]
  - title: "🧰 Maintenance"
    labels: ["chore","refactor","docs"]
  - title: "🔐 Security"
    labels: ["security"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch
template: |
  ## Changes
  $CHANGES
autolabeler:
  - label: "docs"
    files: ["**/*.md","mkdocs.yml","docs/**"]
  - label: "security"
    title: "/(CVE|security)/i"
  - label: "chore"
    files: ["**/*.yml",".github/**"]
