# Release Drafter configuration

# Determine the version numbers and tags based on semantic versioning.
name-template: 'v${{version}}'
tag-template: 'v${{version}}'

# Categorise pull requests based on labels.  Each category is rendered as
# a section in the release notes.  Uncategorised PRs are collected under
# "Miscellaneous" automatically by the action.
categories:
  - title: '🚀 Features'
    labels:
      - enhancement
      - feature
  - title: '🛠️ Fixes'
    labels:
      - bug
      - fix
  - title: '📝 Documentation'
    labels:
      - documentation
  - title: '🧰 Maintenance'
    labels:
      - chore
      - cleanup

# Format each change entry.  The template variables `CONTRIBUTOR`, `TITLE`,
# `PR_NUMBER` and `PR_URL` are provided by the release-drafter action.
change-template: '- ${{CONTRIBUTOR}}: ${{TITLE}} in [#${{PR_NUMBER}}](${{PR_URL}})'

# Overall release notes template.  The `CHANGELOG` and `CONTRIBUTORS`
# placeholders will be replaced with the formatted list of changes and
# contributors.
template: |
  ## What's Changed
  ${{CHANGELOG}}

  ## Contributors
  ${{CONTRIBUTORS}}
