# .github/release-drafter.yml
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug fixes'
    labels: ['bug', 'fix', 'bugfix']
  - title: '⚙️ Performance'
    labels: ['perf', 'performance']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'deps', 'dependencies']
  - title: '🧪 CI / Build'
    labels: ['ci', 'build']
  - title: '📚 Docs'
    labels: ['docs', 'documentation']
  - title: '🔐 Security'
    labels: ['security']

change-template: '- $TITLE (@$AUTHOR) in #$NUMBER'
change-title-escapes: '\<*_&`'   # keep markdown safe

version-resolver:
  major: { labels: ['major'] }
  minor: { labels: ['minor'] }
  patch: { labels: ['patch'] }
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'docs'
    files: ['**/*.md', 'Documents/**', 'Wiki/**']
  - label: 'ci'
    files: ['.github/workflows/**']
  - label: 'security'
    title: ['/security/i']
    files: ['Security/**', '**/SBOM*', '**/spdx*']
  - label: 'feature'
    branch: ['/feature\\/.*|feat\\/.*|enhancement\\/.*|spark\\/.*|proto\\/.*|gcpv\\d+\\.\\d+/i']
  - label: 'bug'
    branch: ['/fix\\/.*|bugfix\\/.*|hotfix\\/.*|patch\\/.*|chore\\/fix.*/i']
  - label: 'perf'
    title: ['/perf|performance|optimi[sz]e/i']
  - label: 'chore'
    files: ['Scripts/**', 'docker/**']
  - label: 'build'
    files: ['docker/**', '**/setup.*', '**/pyproject.toml', '**/package.json']

template: |
  ## What’s Changed

  $CHANGES

  ### Contributors
  $CONTRIBUTORS
