name: "🐞 Bug report"
description: Report a problem with the protocol, scripts, or docs
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Clear, concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to see the issue (code, prompts, inputs).
      render: bash
  - type: input
    id: version
    attributes:
      label: GCP Version
      placeholder: e.g., V47.2
  - type: dropdown
    id: env
    attributes:
      label: Environment
      multiple: true
      options:
        - Local
        - Codespaces
        - Colab
        - Cloud runner (GitHub Actions)
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs (redact secrets).
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues and discussions
          required: true
