blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/lazyxeon/Genesis-Code-Protocol/discussions
    about: Ask usage questions or propose ideas here.
