# .github/workflows/auto-changelog.yml
name: Generate Changelog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for commits
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml  # Assume you add a config file
          args: --output GRCP most recent variants/Changelog.md
      - name: Commit Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Changelog"
