name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Dependabot PR number"
        required: true
        type: number


permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Verify Dependabot author
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.inputs['pr-number']
            });
            if (pr.data.user.login !== 'dependabot[bot]') {
              core.setFailed('PR is not authored by dependabot');
            }
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number || github.event.inputs['pr-number'] }}
          merge-method: squash
