---
name: Auto-merge Dependabot PRs

"on":
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Dependabot PR number"
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-enable-auto-merge:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Dependabot author
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v8
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr-number }}
            });
            if (pr.data.user.login !== 'dependabot[bot]') {
              core.setFailed('PR is not authored by dependabot');
            }

      - name: Run tests
        run: |
          python -m pytest tests/ -v

      - name: Validate automerge functionality
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr-number }}
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
          import os
          from src.automerge import enable_automerge
          pr = int(os.getenv('PR_NUMBER', '0'))
          repo = os.getenv('REPO', '')
          token = os.getenv('GITHUB_TOKEN')
          try:
            result = enable_automerge(pr, repo, token)
            print(f'Auto-merge result: {result}')
            if result['status'] == 'enabled':
              print('✅ Auto-merge enabled successfully')
            else:
              print('ℹ️ Auto-merge was skipped or not enabled')
          except Exception as e:
            print(f'❌ Auto-merge failed: {e}')
            raise
          "

      - name: Enable auto-merge (fallback)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{
            github.event.pull_request.number || inputs.pr-number }}
          merge-method: squash
