name: Auto‑merge Dependabot PRs
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
permissions:
      contents: write
      pull_requests: write
    runs_on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            // merge with squash once all checks have passed
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash'
            });
