---
name: Build and Push Docker image to GHCR
run-name: ${{ github.workflow }}

"on":
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ghcr-${{ github.ref }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Check Dockerfile Python version
        id: check-dockerfile
        run: |
          PYTHON_VERSION=$(grep -oP 'FROM python:\K[0-9.]+' Dockerfile || echo "unknown")
          echo "Detected Python version in Dockerfile: $PYTHON_VERSION"

          if [[ "$PYTHON_VERSION" == "3.13"* ]]; then
            echo "⚠️ Python 3.13 detected in Dockerfile. This version might not be widely available in all environments."
            echo "dockerfile_warning=true" >> $GITHUB_OUTPUT
          else
            echo "dockerfile_warning=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Add warning to job summary
        if: steps.check-dockerfile.outputs.dockerfile_warning == 'true'
        run: |
          echo "⚠️ **Warning**: This workflow is using Python 3.13 in the Dockerfile, which might not be widely available in all environments." >> $GITHUB_STEP_SUMMARY
          echo "Consider updating the Dockerfile to use a more stable Python version like 3.11 or 3.12 if you encounter build issues." >> $GITHUB_STEP_SUMMARY
