# .github/workflows/dependency-review.yml
name: Dependency Review on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run Dependency Review
        # Pin to a valid commit from v4.7.3 tag
        uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b
