---
name: Automatic Dependency Submission (Python)

"on":
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit:
    runs-on: ubuntu-latest
    # The dependency submission API needs write permissions on contents
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Component detection & submit
        uses: advanced-security/component-detection-dependency-submission-action@9c110eb34dee187cd9eca76a652b9f6a0ed22927
        with:
          filePath: .
