name: Automatic Dependency Submission (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write
  dependency-graph: write   # required to submit snapshots

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Component detection & submit
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          filePath: .
          # no unsupported inputs (removed fail-on-error)
