# .github/workflows/dependency-review.yml
name: Dependency Review on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      base_ref:
        description: "Base ref for comparison"
        required: true
      head_ref:
        description: "Head ref for comparison"
        required: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Run Dependency Review
        uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b
        with:
          base-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.inputs.base_ref }}
          head-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.inputs.head_ref }}
          fail-on-severity: high
