---
name: Automatic Dependency Submission (Python)

"on":
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit:
    runs-on: ubuntu-latest
    # The dependency submission API needs write permissions on contents
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Component detection & submit
        uses: advanced-security/component-detection-dependency-submission-action@d433c2f467e149a8009c8fbce92cc708ed15ef7b
        with:
          filePath: .
