name: Automatic Dependency Submission (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Minimal, but enough for dependency submission
permissions:
  contents: write           # required by the Dependency Submission REST API
  security-events: write
  id-token: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Component detection & submit
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          filePath: .
