name: Docker Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'requirements.txt'
      - 'CLI Bundle/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
