---
name: Docker Debug Build

"on":
  workflow_dispatch: {}

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v4
      - name: Show context
        run: |
          pwd && ls -la
          echo "---- head of docker/Dockerfile ----"
          sed -n '1,120p' docker/Dockerfile || true
          echo "---- check requirements file ----"
          ls -la "cli_bundle" || true
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - name: Build (no push)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: local/gcp-protocol:debug
          no-cache: true
