# .github/workflows/docker-debug.yml
name: Docker Debug Build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v5

      - name: Show context
        run: |
          pwd && ls -la
          echo "---- head of docker/Dockerfile ----"
          sed -n '1,120p' docker/Dockerfile || true
          echo "---- check requirements file ----"
          ls -la "CLI Bundle" || true

      - uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: local/gcp-protocol:debug
          no-cache: true
