name: Docker Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
      - 'CLI Bundle/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
      - 'CLI Bundle/**'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: local/gcp-protocol:latest
