name: Docker Build

on:
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
      - 'cli_bundle/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
      - 'cli_bundle/**'
      - 'requirements.txt'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - name: Build image (no push)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: local/gcp-protocol:latest
