name: Generate Changelog

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "CHANGELOG.md"                     # avoid loops
      - "Table Of Contents.md"
      - ".github/workflows/generate-changelog.yml"
      - ".github/workflows/update-toc-file.yml"
      - ".github/workflows/update-repo-structure.yml"
      - "README.md"
  workflow_dispatch: {}                    # manual run
  schedule:
    - cron: "29 3 * * *"                  # optional: daily

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: changelog
  cancel-in-progress: true

jobs:
  changelog:
    if: ${{ github.actor != 'github-actions[bot]' }}   # don't re-run on bot commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate CHANGELOG.md
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
        run: |
          python -V
          python scripts/generate_changelog.py

      - name: Show diff (debug)
        run: |
          git status
          git --no-pager diff -- CHANGELOG.md || true

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-changelog
          title: "chore(docs): refresh CHANGELOG.md"
          commit-message: "docs: auto-update CHANGELOG.md"
          body: |
            This PR updates **CHANGELOG.md** from git history since the last tag.
            Generated by `scripts/generate_changelog.py`.
          labels: documentation
          signoff: true
