name: Generate Changelog

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "CHANGELOG.md"
      - "Table Of Contents.md"
      - ".github/workflows/generate-changelog.yml"
      - ".github/workflows/update-toc-file.yml"
      - ".github/workflows/update-repo-structure.yml"
      - "README.md"
  workflow_dispatch: {}
  schedule:
    - cron: "29 3 * * *"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: changelog
  cancel-in-progress: true

jobs:
  changelog:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "generate_changelog.py" -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate CHANGELOG.md (handles Scripts/ vs scripts/)
        id: gen
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
        run: |
          set -euo pipefail
          if [ -f "Scripts/generate_changelog.py" ]; then
            PY="Scripts/generate_changelog.py"
          elif [ -f "scripts/generate_changelog.py" ]; then
            PY="scripts/generate_changelog.py"
          else
            echo "::error::generate_changelog.py not found in Scripts/ or scripts/"
            exit 1
          fi
          python -V
          python "$PY"
          echo "changed=$(git status --porcelain | grep -c '^ M CHANGELOG.md' || true)" >> "$GITHUB_OUTPUT"

      - name: Show diff (debug)
        run: |
          git --no-pager diff -- CHANGELOG.md || true

      - name: Create PR with changes
        if: steps.gen.outputs.changed != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-changelog
          title: "chore(docs): refresh CHANGELOG.md"
          commit-message: "docs: auto-update CHANGELOG.md"
          body: |
            This PR updates **CHANGELOG.md** from git history since the last tag.
            Generated by `generate_changelog.py`.
          labels: documentation
          signoff: true
