permissions: read-all
jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # ... steps for generating changelog ...
      - name: Commit updated CHANGELOG
        # Pin third-party action to commit SHA
        uses: stefanzweifel/git-auto-commit-action@<commit-sha>
        with:
          commit_message: "chore(changelog): update and normalize spacing"
          file_pattern: CHANGELOG.md
