---
name: Generate Changelog

"on":
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
      - "!CHANGELOG.md"
      - "!.github/workflows/generate-changelog.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  changelog:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies required by the changelog script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps gitpython==3.1.45

      # Count commits since the last changelog update
      - name: Count commits
        id: changes
        run: |
          LAST=$(git log -1 --format=%H -- CHANGELOG.md || echo)
          if [ -z "$LAST" ]; then
            COUNT=$(git rev-list --count HEAD)
          else
            COUNT=$(git rev-list --count "$LAST"..HEAD)
          fi
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          if [ "$COUNT" -ge 5 ]; then
            echo "run_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_pr=false" >> "$GITHUB_OUTPUT"
          fi

      # Generate CHANGELOG.md using your script
      - name: Generate CHANGELOG.md
        if: steps.changes.outputs.run_pr == 'true'
        run: |
          python scripts/generate_changelog.py
          python scripts/fix_md_spacing.py CHANGELOG.md

      # Create a pull request for the changelog update, sign commits with the GitHub Actions bot
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: devops-infra/action-pull-request@v0.6.1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           source_branch: chore/update-repo-structure
           target_branch: main
           title: "chore(docs): sync Repository Structure in README"
           body: "Automated update of the repository structure section."
           labels: documentation
           assignees: ${{ github.actor }}
