name: Build & Push (GHCR)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Buildx (needed even if we call buildx via shell)
      - uses: docker/setup-buildx-action@v3

      - name: Compute image name (lowercase)
        id: vars
        shell: bash
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      # -------- Phase A: local build with FULL logs captured --------
      - name: Local build (no push) with captured logs
        id: local
        shell: bash
        env:
          BUILDKIT_PROGRESS: plain
        run: |
          set -euo pipefail
          mkdir -p build-logs
          # Build on amd64 only for clarity; uses cache if present
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --progress=plain \
            --load \
            -t local/gcp-protocol:debug \
            -f docker/Dockerfile \
            . 2>&1 | tee build-logs/local-build.log
          # Preserve the exit code from buildx through tee
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload local build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-local-build-log
          path: build-logs/local-build.log
          if-no-files-found: error

      # -------- Phase B: only push if local build succeeded ----------
      - uses: docker/login-action@v3
        if: steps.local.outcome == 'success'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push to GHCR (amd64 first)
        if: steps.local.outcome == 'success'
        shell: bash
        env:
          BUILDKIT_PROGRESS: plain
        run: |
          set -euo pipefail
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --progress=plain \
            --push \
            -t "${{ steps.vars.outputs.image }}:latest" \
            -t "${{ steps.vars.outputs.image }}:${GITHUB_SHA}" \
            -f docker/Dockerfile \
            .

      # Fail the job if local build failed (after uploading logs)
      - name: Fail if local build failed
        if: steps.local.outcome != 'success'
        run: |
          echo "Local Docker build failed; see artifact 'docker-local-build-log'."
          exit 1
