# .github/workflows/ghcr-build.yml
name: Build & Push (GHCR)

on:
  push:
    branches: [ "main" ]         # run on pushes to main
    # Optional: limit when it runs
    # paths:
    #   - "docker/Dockerfile"
    #   - "CLI Bundle/**"
    #   - ".github/workflows/ghcr-build.yml"
  workflow_dispatch: {}           # allow manual runs

permissions:
  contents: read
  packages: write                 # needed to push to ghcr.io
  id-token: write                 # optional: enables attestations/provenance

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDKIT_PROGRESS: plain    # show full build logs
    steps:
      - uses: actions/checkout@v4

      # Needed only for multi-arch
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name (lowercase)
        id: vars
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.image }}:latest
            ${{ steps.vars.outputs.image }}:${{ github.sha }}
          provenance: mode=max
          attests: type=sbom
          cache-from: type=gha
          cache-to: type=gha,mode=max
