---
name: Manual Mock Run

"on":
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  trigger-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch security scan in mock mode
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'security-scan.yml',
              ref: context.ref,
              inputs: { mock: 'true' }
            });
            core.info('Security scan mock run dispatched');
