name: Markdownlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Keep it simple: no "config:" input here so CLI2 can auto-discover per-folder configs
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
        with:
          globs: |
            **/*.md
            #node_modules
