name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g markdownlint-cli
      - run: markdownlint '**/*.md' --config .markdownlint.yml --ignore-path .markdownlintignore
