name: Markdownlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19.0.0
        with:
          # Lint everything; we’ll fine-tune rules via .markdownlint*.jsonc below
          globs: |
            **/*.md
          # Point to repo-wide rule config:
          config: .markdownlint.jsonc
