---
name: Markdown Lint

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '.markdownlint.yml'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '.markdownlint.yml'
      - '.github/workflows/markdownlint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install markdownlint-cli2 directly
      - name: Install markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2
          markdownlint-cli2 --version
      
      # Run markdownlint with specific exclusions
      - name: Run DavidAnson/markdownlint-cli2-action@v20
        run: |
          # Create a temporary config file that extends the main config
          cat > .markdownlint-cli2.yaml << EOF
          extends: .markdownlint.yml
          ignores:
            - "Notebooks/**"
            - "Documents/**"
            - "GCP-All-Variants/**"
            - "GCP Runners/**"
            - "cli_bundle/**"
            - "Table Of Contents.md"
            - "GCP Current Version(V50 Flagship Edition).md"
            - "LICENSE.md"
            - "README.md"
            - "Charts.md"
            - "node_modules/**"
          EOF
          
          # Run markdownlint with the temporary config
          # Use --fix to automatically fix common issues
          markdownlint-cli2 --config .markdownlint-cli2.yaml "**/*.md" --fix || true
          
          # Check if there are still issues after fixing
          if ! markdownlint-cli2 --config .markdownlint-cli2.yaml "**/*.md"; then
            echo "::warning::Markdown linting found issues that couldn't be automatically fixed."
            echo "::warning::Consider running 'markdownlint-cli2 --fix' locally to fix these issues."
            # Don't fail the workflow for now
            exit 0
          else
            echo "✅ Markdown linting passed successfully!"
          fi
      
      # If we're on a PR, commit the fixes
      - name: Commit fixes if on PR
        if: github.event_name == 'pull_request'
        run: |
          if git diff --name-only | grep -q '\.md$'; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "docs: fix markdown linting issues [skip ci]"
            git push
          else
            echo "No markdown files were changed, nothing to commit."
          fi