name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: .markdownlint.yml
          globs: |
            **/*.md
            !Notebooks/**
            !Documents/**
            !GCP-All-Variants/**
            !GCP Runners/**
            !cli_bundle/**
            !Table Of Contents.md
            !GCP Current Version(V50 Flagship Edition).md
            !LICENSE.md
            !README.md
            !Charts.md

