name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - run: npm install -g markdownlint-cli@0.45.0
      - run: |
          markdownlint '**/*.md' --config .markdownlint.yml --ignore-path .markdownlintignore || exit_code=$?
          if [ "${exit_code:-0}" -eq 2 ]; then
            echo "No Markdown files to lint."
            exit 0
          else
            exit "${exit_code:-0}"
          fi
