name: OpenSSF Scorecard
on:
  schedule:
    - cron: '23 5 * * 1'
  push:
    branches: [ main ]
  workflow_dispatch:

# Global least privilege
permissions:
  contents: read
  security-events: read

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    runs-on: ubuntu-latest
    # Escalate only what this job needs (now includes id-token for Sigstore/Fulcio)
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
