name: Python CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==23.3.1
          pip install -r requirements.txt ruff==0.4.8
      - name: Lint
        run: ruff check src tests
      - name: Run tests
        run: |
          if [ -d "tests" ] && [ "$(ls -A tests)" ]; then python -m pytest -v; else echo 'No tests found.'; fi
