name: Python CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==23.3.1
          pip install -r requirements.txt
          pip install flake8==7.0.0
      - name: Lint with Flake8
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          python -m flake8 . --count --max-complexity=10 --max-line-length=127 --statistics || true
      - name: Run tests
        run: |
          if [ -d "tests" ] && [ "$(ls -A tests)" ]; then python -m pytest -v; else echo 'No tests found.'; fi
