name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

# Default read‑only permissions for this workflow.  Individual jobs may request
# additional scopes.
permissions:
  contents: read

jobs:
  update_release_draft:
    # This job needs write permissions to create or update release drafts and
    # label pull requests.
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@v6.1.0
        with:
          # Tell the action to use our configuration file.  The default file
          # name is `.github/release-drafter.yml` but we specify it explicitly
          # for clarity.
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
