permissions: read-all
jobs:
  bundle:
    permissions:
      contents: write   # needed to upload assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare staging
        run: |
          # ... existing commands ...
      - name: SBOM (SPDX)
        uses: anchore/sbom-action@<commit-sha>
        with:
          path: .
          format: spdx-json
          output-file: dist/sbom.spdx.json
      - name: SBOM (CycloneDX)
        uses: anchore/sbom-action@<commit-sha>
        with:
          path: .
          format: cyclonedx-json
          output-file: dist/sbom.cdx.json
      - name: SHA-256 checksums
        run: |
          set -euo pipefail
          cd dist
          sha256sum * > SHA256SUMS.txt
      - name: Upload bundle to release
        uses: softprops/action-gh-release@<commit-sha>
        with:
          files: |
            dist/GCP_${{ env.TAG }}_Field_Kit.zip
            dist/sbom.spdx.json
            dist/sbom.cdx.json
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
