name: Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@5a56e55ea7a17ea106d7ec597f1c0f8dbc3f02ac
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
