name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

template: |
  ## Changes
  $CHANGES

# Default read-only permissions.
permissions:
  contents: read

jobs:
  update_release_draft:
    # Needs write permissions for release notes and PR labels.
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      # Use a stable release tag for the release drafter action.  Pinning to a
      # known tag ensures the action is available.
      - uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
