name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

# Default read-only permissions.
permissions:
  contents: read

jobs:
  update_release_draft:
    # Needs write permissions for release notes and PR labels.
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: release-drafter/release-drafter@93a22f86bb189f3c450631e8d012e5d208a6446b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
