name: Sign releases with cosign

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  sign-release:
    name: Sign release artifacts with cosign (keyless)
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      COSIGN_EXPERIMENTAL: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install cosign (keyless)
        uses: sigstore/cosign-installer@f3e9b7d72b807f8cdb3c1e232d5a8d60061c4a09

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          mkdir -p artifacts
          gh release download "$TAG" --repo "${GITHUB_REPOSITORY}" --dir artifacts
          ls -lah artifacts

      - name: Sign assets
        run: |
          set -euo pipefail
          cd artifacts
          shopt -s nullglob
          for f in *; do
            [ -f "$f" ] || continue
            echo "Signing $f"
            cosign sign-blob --yes --output-signature "$f.sig" "$f"
          done
          ls -lah

      - name: Upload signatures
        uses: softprops/action-gh-release@e7a8b55abb8e23f972de3b0cb6a4f5b9d1bf0f0b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: artifacts/*.sig
