name: Generate SBOM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Build SBOM (CycloneDX)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@d4e4ab0d3ab35bb04c9a01d256d661a8603e54b3
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: sbom-cyclonedx
          path: sbom.cyclonedx.json

      - name: Print summary (optional)
        run: |
          jq -r '.metadata.component.name, .metadata.component.version' sbom.cyclonedx.json || true
