name: Generate SBOM

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Generate SBOM (SPDX JSON) with Syft
        uses: anchore/sbom-action@da167eac915b4e86f08b264dbdbc867b61be6f0c
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: sbom-spdx
          path: sbom.spdx.json
