name: SBOM (Release)

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@v0.16.0
        with:
          path: .
          output-file: sbom.cdx.json
          format: cyclonedx-json

      - name: Generate SBOM (SPDX JSON)
        uses: anchore/sbom-action@v0.16.0
        with:
          path: .
          output-file: sbom.spdx.json
          format: spdx-json

      - name: Upload SBOMs to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.cdx.json
            sbom.spdx.json
