name: Scorecard
on:
  schedule: [{cron: '0 12 * * 1'}]
  push: {branches: [main]}
permissions: {security-events: write, id-token: write, contents: read}
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: {sarif_file: results.sarif}
