name: OpenSSF Scorecard

on:
  schedule:
    # Run Scorecard weekly at 02:00 UTC on Sundays
    - cron: "0 2 * * 0"
  workflow_dispatch:

# Grant read access by default. Scorecard requires id-token and security-events
# permissions at the job level for uploading SARIF results.
permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@9c5a5773a477a6918c1b33cd94e587f3a6316d94
        with:
          results_file: scorecard-results.sarif
          publish_results: true
      - name: Upload Scorecard results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scorecard-results.sarif
