name: OpenSSF Scorecard

on:
  schedule:
    # Run Scorecard weekly at 02:00 UTC on Sundays
    - cron: '0 2 * * 0'
  workflow_dispatch:

# Grant read‑only permissions by default.  The job requests additional
# permissions for uploading SARIF results.
permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.2
        with:
          # Write the results to a SARIF file so that they can be uploaded to
          # GitHub and displayed in the Security tab.
          results_file: scorecard-results.sarif
          results_format: sarif
      - name: Upload Scorecard results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scorecard-results.sarif
