# .github/workflows/security-scan.yml
name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install safety and bandit
        run: pip install safety bandit
      - name: Run Safety check
        continue-on-error: true  # Treat as warning; fail only if critical
        run: safety check --full-report || echo "Safety warnings found; review manually."
      - name: Run Bandit for code security
        continue-on-error: true
        run: bandit -r . || echo "Bandit findings; review for fixes."
