name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# The workflow uses only read access.  It installs dependencies and runs
# static analysis tools.
permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'
      - name: Install scanning tools
        # Install Bandit and Safety at fixed versions to ensure
        # reproducibility and satisfy the pinned‑dependencies rule.
        run: |
          python -m pip install --upgrade pip
          pip install bandit==1.7.5 safety==2.3.5
      - name: Run Bandit
        run: bandit -r . || true
      - name: Run Safety
        run: safety check || true
