---
name: Security Scan

"on":
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      mock:
        description: "Run in mock mode without executing scanners"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install scanning tools
        run: |
          python -m pip install --upgrade pip==23.3.1
          pip install --no-deps bandit==1.7.5 safety==2.3.5
      - name: Mock run notice
        if: ${{ github.event.inputs.mock == 'true' }}
        run: echo "Mock run - scanners skipped"
      - name: Run Bandit
        if: ${{ github.event.inputs.mock != 'true' }}
        run: bandit -r . || true
      - name: Run Safety
        if: ${{ github.event.inputs.mock != 'true' }}
        run: safety check || true
