name: Update Repo Structure

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Build repo tree and patch README
        run: |
          python scripts/update_repo_structure.py
          python scripts/fix_md_spacing.py README.md

      # Create a PR for the README update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          commit-message: "docs(readme): auto-sync repo structure"
          branch: "chore/update-repo-structure"
          title: "chore(docs): sync Repository Structure in README"
          body: "Automated update of the repository structure section."
          labels: "documentation"
          add-paths: "README.md"
          sign-commits: true
