name: Update Repo Structure

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
      - name: Build repo tree and patch README
        run: |
          # (inline Python unchanged from original; omitted here for brevity)
          python - <<'PY'
          # ... original Python script ...
          PY

      # Install gitsign and configure git
      - name: Install gitsign
        run: |
          go install github.com/sigstore/gitsign@v0.7.1
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Configure git for commit signing
        run: |
          git config --local user.name "${{ github.workflow_ref }}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local commit.gpgsign true
          git config --local gpg.format x509
          git config --local gpg.x509.program gitsign

      # Create branch, sign commit, and push
      - name: Commit and push README
        run: |
          BRANCH="chore/update-repo-structure"
          git switch --create "$BRANCH"
          git add README.md
          git commit -m "docs(readme): auto-sync repo structure" -S
          git push --set-upstream origin "$BRANCH"

      # Create PR with gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore(docs): sync Repository Structure in README" \
            --body "Automated update of the repository structure section." \
            --head "$BRANCH" \
            --base main \
            --label documentation
