name: Update Repo Structure

on:
  push:
    branches: [ "main" ]
    # prevent infinite loop when our own PR touches README
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  workflow_dispatch: {}        # manual "Run workflow" button
  schedule:
    - cron: "17 2 * * *"       # optional: daily at 02:17 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build repo tree and patch README (inline)
        id: patch
        run: |
          python - <<'PY'
          import os, re, sys
          from pathlib import Path

          ROOT = Path(".").resolve()
          README = ROOT / "README.md"
          BEGIN = "<!-- BEGIN REPO TREE -->"
          END = "<!-- END REPO TREE -->"

          EXCLUDE_DIRS = {
              ".git", ".github", "__pycache__", ".mypy_cache", ".pytest_cache",
              ".venv", "venv", "node_modules", "dist", "build", ".idea", ".vscode"
          }
          EXCLUDE_FILES = {".DS_Store"}
          MAX_DEPTH = 2
