name: Update Repo Structure

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"                      # avoid loops when only README changes
      - ".github/workflows/update-repo-structure.yml"
  workflow_dispatch: {}                  # adds a manual "Run workflow" button
  schedule:
    - cron: "17 2 * * *"                # optional: run daily at 02:17 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  generate-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ref: main   # (optional) pin explicitly if you ever use schedules only

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate repo tree
        run: |
          python -V
          python scripts/update_repo_structure.py

      - name: Show diff (debug)
        run: |
          echo "---- git status ----"
          git status
          echo "---- diff README.md ----"
          git --no-pager diff -- README.md || true

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-repo-structure
          title: "chore(docs): sync Repository Structure in README"
          commit-message: "chore(docs): auto-sync repo structure in README"
          body: |
            This PR updates the auto-generated **Repository Structure** section in `README.md`.
            The content between the markers is generated by `scripts/update_repo_structure.py`.
          labels: documentation
          signoff: true
