name: Update Top-Level TOC file

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "Table Of Contents.md"
      - ".github/workflows/update-toc-file.yml"
  schedule:
    - cron: "21 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: toc-file
  cancel-in-progress: true

jobs:
  build-toc:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
      - name: Generate "Table Of Contents.md" (inline)
        run: |
          # (inline Python unchanged from original; omitted here)
          python - <<'PY'
          # ... original Python script ...
          PY
      - name: Show diff (debug)
        run: |
          git status
          git --no-pager diff -- "Table Of Contents.md" || true

      # Install gitsign and configure git
      - name: Install gitsign
        run: |
          go install github.com/sigstore/gitsign@v0.7.1
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Configure git for commit signing
        run: |
          git config --local user.name "${{ github.workflow_ref }}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local commit.gpgsign true
          git config --local gpg.format x509
          git config --local gpg.x509.program gitsign

      # Create branch, sign commit, push
      - name: Commit and push TOC
        run: |
          BRANCH="chore/update-top-level-toc"
          git switch --create "$BRANCH"
          git add "Table Of Contents.md"
          git commit -m "docs: auto-update Table Of Contents.md" -S
          git push --set-upstream origin "$BRANCH"

      # Create PR using gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore(docs): refresh Table Of Contents.md" \
            --body "Automated TOC update." \
            --head "$BRANCH" \
            --base main \
            --label documentation
