name: Update Top-Level TOC file

on:
  push:
    paths-ignore:
      - "Table Of Contents.md"
      - ".github/workflows/update-toc-file.yml"
  schedule:
    - cron: "21 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: toc-file
  cancel-in-progress: true

jobs:
  build-toc:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate "Table Of Contents.md"
        run: |
          python scripts/generate_repo_toc.py
          python scripts/fix_md_spacing.py "Table Of Contents.md"

      # Show the diff (optional for debugging)
      - name: Show diff
        run: |
          git status
          git --no-pager diff -- "Table Of Contents.md" || true

      # Create a PR for the TOC update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: "docs: auto-update Table Of Contents.md"
          branch: "chore/update-top-level-toc"
          title: "chore(docs): refresh Table Of Contents.md"
          body: "Automated TOC update."
          labels: "documentation"
          add-paths: "Table Of Contents.md"
          sign-commits: true
