name: Update Top-Level TOC file

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "Table Of Contents.md"
      - ".github/workflows/update-toc-file.yml"
  workflow_dispatch: {}
  schedule:
    - cron: "21 3 * * *"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: toc-file
  cancel-in-progress: true

jobs:
  build-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Quick debug (show tree)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "generate_repo_toc.py" -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate TOC file (handles Scripts/ vs scripts/)
        run: |
          set -euo pipefail
          if [ -f "Scripts/generate_repo_toc.py" ]; then
            PY_PATH="Scripts/generate_repo_toc.py"
          elif [ -f "scripts/generate_repo_toc.py" ]; then
            PY_PATH="scripts/generate_repo_toc.py"
          else
            echo "::error::generate_repo_toc.py not found in Scripts/ or scripts/"
            exit 1
          fi
          python -V
          python "$PY_PATH"

      - name: Show diff (debug)
        run: |
          echo "---- git status ----"
          git status
          echo "---- diff ----"
          git --no-pager diff -- "Table Of Contents.md" || true

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-top-level-toc
          title: "chore(docs): refresh Table Of Contents.md"
          commit-message: "docs: auto-update Table Of Contents.md"
          body: |
            This PR auto-refreshes **Table Of Contents.md** with working links.
            Generated by `Scripts/generate_repo_toc.py`.
          labels: documentation
          signoff: true
