name: Update Top-Level TOC file

on:
  push:
    branches:
      - main
    paths-ignore:
      - "Table Of Contents.md"
      - ".github/workflows/update-toc-file.yml"
  schedule:
    - cron: "21 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: toc-file
  cancel-in-progress: true

jobs:
  build-toc:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: chore/update-top-level-toc
      PR_TITLE: "chore(docs): refresh Table Of Contents.md"
      TOC_FILE: "Table Of Contents.md"

    steps:
      - name: Checkout repository (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Validate scripts exist
        run: |
          set -euo pipefail
          for f in scripts/generate_repo_toc.py scripts/fix_md_spacing.py; do
            if [ ! -f "$f" ]; then
              echo "Error: $f not found"
              exit 1
            fi
          done
          echo "✓ All required scripts found"

      - name: Generate Table Of Contents
        run: |
          set -euo pipefail
          echo "Generating $TOC_FILE..."
          python scripts/generate_repo_toc.py
          if [ ! -f "$TOC_FILE" ]; then
            echo "Error: $TOC_FILE was not generated"
            exit 1
          fi
          echo "Formatting $TOC_FILE..."
          python scripts/fix_md_spacing.py "$TOC_FILE"
          echo "✓ $TOC_FILE generated and formatted successfully"

      - name: Detect changes
        id: changes
        run: |
          set -euo pipefail
          if git diff --quiet -- "$TOC_FILE"; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected in $TOC_FILE"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "Changes detected in $TOC_FILE"
          fi

      - name: Show diff
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          set -euo pipefail
          echo "Git diff for $TOC_FILE:"
          git --no-pager diff -- "$TOC_FILE"

      - name: Commit & push branch
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          set -euo pipefail
          git switch -C "$BRANCH_NAME"
          git add "$TOC_FILE"
          if git diff --cached --quiet; then
            echo "No staged changes after branch switch; exiting."
            exit 0
          fi
            git commit -m "docs: auto-update Table Of Contents.md"
          git push -f origin "$BRANCH_NAME"

      - name: Create or Update Pull Request
        id: pr
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
          PR_BODY: |
            ## Automated Table Of Contents Update

            This PR contains an automated update to the repository Table Of Contents.

            ### Changes
            - Updated `Table Of Contents.md` with current repository structure
            - Applied markdown spacing normalization

            ### Triggered by
            - Workflow: ${{ github.workflow }}
            - Event: ${{ github.event_name }}
            - Commit: ${{ github.sha }}
        run: |
          set -euo pipefail
          owner="${REPO%%/*}"
          existing_pr_number="$(gh pr list --state open --head "${owner}:${BRANCH_NAME}" --json number --jq '.[0].number // empty')"

          if [ -n "$existing_pr_number" ]; then
            echo "PR #$existing_pr_number already exists - updating."
            gh pr comment "$existing_pr_number" --body "Automated update pushed: \`${GITHUB_SHA}\`"
            gh pr edit "$existing_pr_number" --add-label "documentation" --add-label "automated"
            echo "pr_number=$existing_pr_number" >> "$GITHUB_OUTPUT"
          else
            echo "Creating new PR..."
            printf '%s\n' "$PR_BODY" > pr_body.md
            gh pr create \
              --base main \
              --head "$BRANCH_NAME" \
              --title "$PR_TITLE" \
              --body-file pr_body.md \
              --label "documentation" \
              --label "automated"
            new_pr="$(gh pr list --state open --head "${owner}:${BRANCH_NAME}" --json number --jq '.[0].number // empty')"
            [ -n "$new_pr" ] && echo "pr_number=$new_pr" >> "$GITHUB_OUTPUT"
          fi

      - name: Log result
        run: |
          if [ "${{ steps.changes.outputs.has_changes }}" = "true" ]; then
            if [ -n "${{ steps.pr.outputs.pr_number }}" ]; then
              echo "✓ Pull request #${{ steps.pr.outputs.pr_number }} created or updated for TOC update"
            else
              echo "✓ Pull request created or updated for TOC update"
            fi
          else
            echo "✓ No changes needed - Table Of Contents is up to date"
