name: Update Top-Level TOC file

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "Table Of Contents.md"               # avoid loops
      - ".github/workflows/update-toc-file.yml"
  workflow_dispatch: {}                      # manual "Run workflow" button
  schedule:
    - cron: "21 3 * * *"                     # optional: daily at 03:21 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: toc-file
  cancel-in-progress: true

jobs:
  build-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate TOC file
        run: |
          python -V
          python scripts/generate_repo_toc.py

      - name: Show diff (debug)
        run: |
          echo "---- git status ----"
          git status
          echo "---- diff ----"
          git --no-pager diff -- "Table Of Contents.md" || true

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-top-level-toc
          title: "chore(docs): refresh Table Of Contents.md"
          commit-message: "docs: auto-update Table Of Contents.md"
          body: |
            This PR auto-refreshes **Table Of Contents.md** with working links.
            Generated by `scripts/generate_repo_toc.py`.
          labels: documentation
          signoff: true
