name: Update Repo Structure

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build repo tree and patch README
        run: |
          python scripts/update_repo_structure.py
          python scripts/fix_md_spacing.py README.md

      # Create a PR for the README update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: "docs(readme): auto-sync repo structure"
          branch: "chore/update-repo-structure"
          title: "chore(docs): sync Repository Structure in README"
          body: "Automated update of the repository structure section."
          labels: "documentation"
          add-paths: "README.md"
