name: Update Repo Structure

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  workflow_dispatch: {}
  schedule:
    - cron: "17 2 * * *"

permissions:
  contents: read

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
      - name: Build repo tree and patch README (inline)
        id: patch
        run: |
          python - <<'PY'
          (python script unchanged)
          PY
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          branch: chore/update-repo-structure
          title: "chore(docs): sync Repository Structure in README"
          commit-message: "docs(readme): auto-sync repo structure"
          labels: documentation
          signoff: true
