---
name: Update Repo Structure

"on":
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".github/workflows/update-repo-structure.yml"
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: repo-structure
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build repo tree and patch README
        run: |
          python scripts/update_repo_structure.py
          if [ -f "README.md" ]; then
            python scripts/fix_md_spacing.py README.md
          else
            echo "Error: README.md not found"
            exit 1
          fi

      # Show the diff (optional for debugging)
      - name: Show diff
        run: |
          git status
          git --no-pager diff -- README.md || true

      # Check if README.md changed
      - name: Detect changes
        id: changes
        run: |
          if git status --porcelain README.md | grep .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      # Create a PR for the README update
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs(readme): auto-sync repo structure"
          branch: "chore/update-repo-structure"
          base: main
          title: "chore(docs): sync Repository Structure in README"
          body: "Automated update of the repository structure section."
          labels: "documentation"
          add-paths: "README.md"
